### ISSUE TITLE
有关“商业限制”的

### ISSUE THREAD

**Issue by happyvalley-lmx** [Nonprofit-Minecraft/Convention#4]
“不允许以任何形式收取入服费用”一项其实并不合理
通过**在线验证**的服务器实际上是可以按照服务器商业化中提及到的
“You are allowed to charge players to access your server”
来进行收费的

我认为，既然有考虑到设置**商业限制**相关的内容，就应该更细致的考虑与撰写相关的条约内容

**Comment by sotr2333** [comment]
依据「相容性条例」，此部分的内容（商业方针中关于入服费用的内容）属于比公约更宽松的要求，固应当遵循公约要求，并不冲突。另外，如果完全依据EULA和商业方针，完全是所谓商业服务器的标准。

**Comment by sotr2333** [comment]
Talked in QQ, resolved.
